name: mkdocs-mike-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: docs-deploy
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VER=$( CI/inject_version.sh )
          MAJMIN=$(echo ${VER} | grep -o '[0-9]\+\.[0-9]\+')
          git config user.name "GitHub Actions CI Publisher"
          git config user.email "DyalogGithubActions@github.com"
          
          mike deploy ${MAJMIN}
          mike alias --update-aliases --push ${MAJMIN} dev