name: mkdocs-mike-deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs_deploy:
    runs-on: ubuntu-latest
    container: rikedyp/dtools

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: docs-deploy
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VER=$( CI/inject_version.sh )
          MAJMIN=$(echo ${VER} | grep -o '[0-9]\+\.[0-9]\+')
          git config user.name "GitHub Actions CI Publisher"
          git config user.email "DyalogGithubActions@github.com"
          
          mike deploy ${MAJMIN}
          mike alias --update-aliases --push ${MAJMIN} dev